{{{template "snippets/docker-compose/container-name.yml" .}}}
services:
  {{{- template "snippets/docker-compose/php.yml" .}}}
  {{{- template "snippets/docker-compose/php-xdebug.yml" .}}}
  {{{- template "snippets/docker-compose/shopware-messenger.yml" .}}}
  {{{- template "snippets/docker-compose/nginx.yml" .}}}
  {{{- template "snippets/docker-compose/db.yml" .}}}
  {{{- template "snippets/docker-compose/db-postgresql.yml" .}}}
  {{{- template "snippets/docker-compose/db-mongodb.yml" .}}}
  {{{- template "snippets/docker-compose/db2.yml" .}}}
  {{{- template "snippets/docker-compose/nodejs.yml" .}}}
  {{{- template "snippets/docker-compose/elasticsearch.yml" .}}}
  {{{- template "snippets/docker-compose/opensearch.yml" .}}}
  {{{- template "snippets/docker-compose/redis.yml" .}}}
  {{{- template "snippets/docker-compose/valkey.yml" .}}}
  {{{- template "snippets/docker-compose/memcached.yml" .}}}
  {{{- template "snippets/docker-compose/rabbitmq.yml" .}}}
  {{{- template "snippets/docker-compose/artemis.yml" .}}}
  {{{- template "snippets/docker-compose/phpmyadmin.yml" .}}}
  {{{- template "snippets/docker-compose/phpmyadmin2.yml" .}}}
  {{{- template "snippets/docker-compose/pgadmin.yml" .}}}
  {{{- template "snippets/docker-compose/mongo-express.yml" .}}}
  {{{- template "snippets/docker-compose/kibana.yml" .}}}
  {{{- template "snippets/docker-compose/opensearchdashboard.yml" .}}}
  {{{- template "snippets/docker-compose/varnish.yml" .}}}
  {{{- template "snippets/docker-compose/grafana.yml" .}}}
  {{{- template "snippets/docker-compose/grafana-loki.yml" .}}}
  {{{- template "snippets/docker-compose/grafana-promtail.yml" .}}}
  {{{- template "snippets/docker-compose/grafana-prometheus.yml" .}}}
  {{{- template "snippets/docker-compose/grafana-mysql-exporter.yml" .}}}
  {{{- template "snippets/docker-compose/grafana-rabbitmq-exporter.yml" .}}}
  {{{- template "snippets/docker-compose/claude.yml" .}}}
  {{{- template "snippets/docker-compose/worker.yml" .}}}

{{{template "snippets/docker-compose/volumes.yml" .}}}
{{{template "snippets/docker-compose/networks.yml" .}}}