{{{template "snippets/dockerfile/nodejs/header" .}}}
{{{template "snippets/dockerfile/nodejs/packages" .}}}
{{{template "snippets/dockerfile/nodejs/cron" .}}}
{{{template "snippets/dockerfile/nodejs/chown" .}}}
{{{template "snippets/dockerfile/nodejs/footer" .}}}