{{{include snippets/dockerfile/nodejs/header}}}
{{{include snippets/dockerfile/nodejs/packages}}}
{{{include snippets/dockerfile/nodejs/cron}}}
{{{include snippets/dockerfile/nodejs/chown}}}
{{{include snippets/dockerfile/nodejs/footer}}}