{
 "title": "RabbitMQ",
 "description": "RabbitMQ Metrics Dashboard",
 "tags": [ "rabbitmq" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Queues",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_queues" }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_connections" }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_channels" }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rabbitmq_consumers" }
   ]
  },
  {
   "title": "Messages Ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rabbitmq_queue_messages_ready", "legendFormat": "{{queue}}" }
   ]
  },
  {
   "title": "Messages Unacknowledged",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_unacked",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Published Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_published_total[1m])",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Messages Delivered Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(rabbitmq_queue_messages_delivered_total[1m])",
     "legendFormat": "{{queue}}"
    }
   ]
  }
 ]
}