package helper

import (
	"fmt"
	"github.com/faradey/madock/src/cli/fmtc"
)

func Help() {
	/* 16 commands */
	fmtc.WarningLn("Usage:")
	tab()
	fmt.Println("command [arguments]")
	fmtc.WarningLn("Available commands:")
	tab()
	fmtc.Success("bash")
	tab()
	fmt.Println("Connect into container using bash")
	tab()
	tab()
	fmtc.Title("--name")
	tab()
	fmt.Print("Name of container. Optional [Default container: php]. For example: --name php, --name node, --name db, --name nginx")
	tabln()
	tab()
	tab()
	fmtc.Title("--root")
	tab()
	fmt.Println("Enter to container as root. Optional")
	tabln()
	tab()
	fmtc.Success("composer")
	tab()
	fmt.Println("Execute composer inside php container")
	tabln()
	tab()
	fmtc.Success("config")
	tab()
	fmt.Println("Viewing and changing the project configuration")
	tab()
	tab()
	fmtc.Warning("show")
	tab()
	fmt.Println("List all project environment settings")
	tab()
	tab()
	fmtc.Warning("set")
	tab()
	fmt.Println("Set parameters")
	tab()
	tab()
	tab()
	fmtc.Title("--hosts")
	tab()
	fmt.Println("Domains and code of project websites. Separated by commas. For example: one.example.com:base two.example.com:two_code. Optional")
	tabln()
	tab()
	fmtc.Success("cron")
	tab()
	fmt.Println("Enable / disable cron")
	tab()
	tab()
	fmtc.Title("--on")
	tab()
	fmt.Println("Enable cron")
	tab()
	tab()
	fmtc.Title("--off")
	tab()
	fmt.Println("Disable cron")
	tabln()
	tab()
	fmtc.Success("db")
	tab()
	fmt.Println("Database import / export")
	tab()
	tab()
	fmtc.Title("--import")
	tab()
	fmt.Println("Database import")
	tab()
	tab()
	fmtc.Title("--export")
	tab()
	fmt.Println("Database export")
	tabln()
	tab()
	fmtc.Success("debug")
	tab()
	fmt.Println("Enable / disable xdebug")
	tab()
	tab()
	fmtc.Title("--on")
	tab()
	fmt.Println("Enable xdebug")
	tab()
	tab()
	fmtc.Title("--off")
	tab()
	fmt.Println("Disable xdebug")
	tabln()
	tab()
	fmtc.Success("help")
	tab()
	fmt.Println("Displays help for commands")
	tabln()
	tab()
	fmtc.Success("logs")
	tab()
	fmt.Println("View logs of a container")
	tab()
	tab()
	fmtc.Title("--[name of container]")
	tab()
	fmt.Println("Container name")
	tabln()
	tab()
	fmtc.Success("magento")
	tab()
	fmt.Println("Execute Magento command inside php container")
	tabln()
	tab()
	fmtc.Success("node")
	tab()
	fmt.Println("Execute NodeJs command inside php container")
	tabln()
	tab()
	fmtc.Success("prune")
	tab()
	fmt.Println("Stop and delete running project containers")
	tab()
	tab()
	fmtc.Title("--all")
	tab()
	fmt.Println("Stop all containers of the project along with the nginx proxy")

	fmt.Println("")
}

func tab() {
	fmt.Print("	")
}

func tabln() {
	fmt.Println("	")
}
