  {{{- if .claude.enabled}}}
  claude:
    init: true
    build:
      context: ctx
      dockerfile: claude.Dockerfile
    tty: true
    volumes:
      - ./src:/var/www/html:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"
      {{{- range .nginx.hosts}}}
      - "{{{.name}}}:host-gateway"
      {{{- end}}}
    restart: {{{.restart_policy}}}
  {{{- end}}}
  {{{- if and .claude.enabled .isolation.enabled}}}
  networks:
    - isolated
  {{{- end}}}