<<<if{{{db/type_is_postgresql}}}>>>
  db:
    init: true
    build:
      context: ctx
      dockerfile: db.Dockerfile
    ports:
      - "{{{port/db}}}:5432"
    environment:
      POSTGRES_DB: "{{{db/database}}}"
      POSTGRES_USER: "{{{db/user}}}"
      POSTGRES_PASSWORD: "{{{db/password}}}"
    volumes:
      - dbdata:/var/lib/postgresql/data
    <<<if{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>
    restart: {{{restart_policy}}}
<<<endif>>>