{{{- if .grafana.enabled}}}
  dbexporter:
    init: true
    image: {{{.grafana.mysqld_exporter.repository}}}:{{{.grafana.mysqld_exporter.version}}}
    volumes:
      - ./ctx/grafana/mysql-exporter.my.cnf:/.my.cnf
    networks:
      - default
      {{{- if .isolation.enabled}}}
      - isolated
      {{{- end}}}
    restart: {{{.restart_policy}}}
{{{- end}}}