<<<if{{{grafana/enabled}}}>>>
  promtail:
    image: grafana/promtail:2.9.10
    volumes:
      - ./ctx/grafana/promtail-config.yml:/etc/promtail/config.yml
      - ./src/var/log:/var/log
    command: --config.file=/etc/promtail/config.yml
    depends_on:
      - loki
    restart: {{{restart_policy}}}
<<<endif>>>
    <<<if{{{grafana/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>