{{{- if .grafana.enabled}}}
  loki:
    init: true
    image: {{{.grafana.loki.repository}}}:{{{.grafana.loki.version}}}
    command: --config.file=/etc/loki/local-config.yaml
    user: root
    volumes:
      - ./ctx/grafana/loki-config.yaml:/etc/loki/local-config.yaml
      - lokidata:/loki
    networks:
      - default
      {{{- if .isolation.enabled}}}
      - isolated
      {{{- end}}}
    restart: {{{.restart_policy}}}
{{{- end}}}