{{{- if .memcached.enabled}}}
  memcached:
    init: true
    image: {{{.memcached.repository}}}:{{{.memcached.version}}}
    command: ["-m", "{{{.memcached.memory}}}", "-c", "{{{.memcached.max_connections}}}"]
    restart: {{{.restart_policy}}}
{{{- end}}}
    {{{- if and .memcached.enabled .isolation.enabled}}}
    networks:
      - isolated
    {{{- end}}}