<<<if{{{db/mongo_express/enabled}}}>>>
  mongo-express:
    init: true
    image: {{{db/mongo_express/repository}}}:{{{db/mongo_express/version}}}
    ports:
      - "{{{port/mongo_express}}}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: {{{db/user}}}
      ME_CONFIG_MONGODB_ADMINPASSWORD: {{{db/password}}}
      ME_CONFIG_MONGODB_SERVER: db
    depends_on:
      - db
    networks:
      - default
<<<if{{{isolation/enabled}}}>>>      - isolated<<<endif>>>
    restart: {{{restart_policy}}}
<<<endif>>>
