{{{- if .search.opensearch.enabled}}}
  opensearch:
    init: true
    build:
      context: ctx
      dockerfile: opensearch.Dockerfile
    deploy:
      resources:
        limits:
          memory: {{{.search.opensearch.memory_limit}}}
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      OPENSEARCH_DISCOVERY_TYPE: 'single-node'
      DISABLE_INSTALL_DEMO_CONFIG: 'true'
      DISABLE_SECURITY_PLUGIN: 'true'
      OPENSEARCH_JAVA_OPTS: '-Xms{{{.search.opensearch.heap}}} -Xmx{{{.search.opensearch.heap}}}'
    volumes:
      - opensearch_vlm_{{{.search.opensearch.version}}}:/usr/share/opensearch/data
    restart: {{{.restart_policy}}}
{{{- end}}}
    {{{- if and .search.opensearch.enabled .isolation.enabled}}}
    networks:
      - isolated
    {{{- end}}}