{{{- if .redis.enabled}}}
  redisdb:
    init: true
    build:
      context: ctx
      dockerfile: redis.Dockerfile
    restart: {{{.restart_policy}}}
{{{- end}}}
    {{{- if and .redis.enabled .isolation.enabled}}}
    networks:
      - isolated
    {{{- end}}}