<<<if{{{redis/enabled}}}>>>
  redisdb:
    build:
      context: ctx
      dockerfile: redis.Dockerfile
    restart: {{{restart_policy}}}
<<<endif>>>
    <<<if{{{redis/enabled}}}{{{isolation/enabled}}}>>>networks:
      - isolated<<<endif>>>