{{{- if .magento.mftf.enabled}}}
  selenium:
    init: true
    image: {{{.magento.mftf.selenium.repository}}}:{{{.magento.mftf.selenium.version}}}
    platform: linux/amd64
    ports:
      - "{{{port "selenium"}}}:7900"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      {{{- range $host := .nginx.hosts}}}
      - "{{{$host.name}}}:host-gateway"
      {{{- end}}}
    shm_size: '2g'
    depends_on:
      - php
    networks:
      - default
      {{{- if .isolation.enabled}}}
      - isolated
      {{{- end}}}
    restart: {{{.restart_policy}}}
{{{- end}}}