{{{- if .valkey.enabled}}}
  valkeydb:
    init: true
    image: {{{.valkey.repository}}}:{{{.valkey.version}}}
    restart: {{{.restart_policy}}}
{{{- end}}}
    {{{- if and .valkey.enabled .isolation.enabled}}}
    networks:
      - isolated
    {{{- end}}}