{{{include snippets/docker-compose/container-name.yml}}}
services:
  {{{include snippets/docker-compose/nginx.yml}}}
  {{{include snippets/docker-compose/ruby.yml}}}
  {{{include snippets/docker-compose/spree-storefront.yml}}}
  {{{include snippets/docker-compose/spree-sidekiq.yml}}}
  {{{include snippets/docker-compose/db.yml}}}
  {{{include snippets/docker-compose/db-postgresql.yml}}}
  {{{include snippets/docker-compose/redis.yml}}}
  {{{include snippets/docker-compose/valkey.yml}}}
  {{{include snippets/docker-compose/pgadmin.yml}}}
  {{{include snippets/docker-compose/claude.yml}}}

{{{include snippets/docker-compose/volumes.yml}}}
{{{include snippets/docker-compose/networks.yml}}}
