version: "3.7"
services:
  nginx:
    container_name: nginx
    build:
      context: ctx
      dockerfile: Dockerfile
    volumes:
{{{VOLUMES}}}
    ports:
      - "80:80"
    networks:
      madock_net:


networks:
  madock_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.90.0/24
