// Package all provides a single blank import that registers every built-in
// madock controller. Import this package for its side effects to register
// all commands at once:
//
//	_ "github.com/faradey/madock/v3/src/controller/all"
package all

import (
	_ "github.com/faradey/madock/v3/src/controller/general/bash"
	_ "github.com/faradey/madock/v3/src/controller/general/claude"
	_ "github.com/faradey/madock/v3/src/controller/general/clean_cache"
	_ "github.com/faradey/madock/v3/src/controller/general/cli"
	_ "github.com/faradey/madock/v3/src/controller/general/composer"
	_ "github.com/faradey/madock/v3/src/controller/general/config"
	_ "github.com/faradey/madock/v3/src/controller/general/cron"
	_ "github.com/faradey/madock/v3/src/controller/general/db/export"
	_ "github.com/faradey/madock/v3/src/controller/general/db/import"
	_ "github.com/faradey/madock/v3/src/controller/general/db/info"
	_ "github.com/faradey/madock/v3/src/controller/general/debug"
	_ "github.com/faradey/madock/v3/src/controller/general/diff"
	_ "github.com/faradey/madock/v3/src/controller/general/help"
	_ "github.com/faradey/madock/v3/src/controller/general/info"
	_ "github.com/faradey/madock/v3/src/controller/general/info/ports"
	_ "github.com/faradey/madock/v3/src/controller/general/install"
	_ "github.com/faradey/madock/v3/src/controller/general/logs"
	_ "github.com/faradey/madock/v3/src/controller/general/node"
	_ "github.com/faradey/madock/v3/src/controller/general/open"
	_ "github.com/faradey/madock/v3/src/controller/general/patch"
	_ "github.com/faradey/madock/v3/src/controller/general/project/clone"
	_ "github.com/faradey/madock/v3/src/controller/general/project/remove"
	_ "github.com/faradey/madock/v3/src/controller/general/proxy"
	_ "github.com/faradey/madock/v3/src/controller/general/prune"
	_ "github.com/faradey/madock/v3/src/controller/general/rebuild"
	_ "github.com/faradey/madock/v3/src/controller/general/remote_sync/db"
	_ "github.com/faradey/madock/v3/src/controller/general/remote_sync/file"
	_ "github.com/faradey/madock/v3/src/controller/general/remote_sync/media"
	_ "github.com/faradey/madock/v3/src/controller/general/restart"
	_ "github.com/faradey/madock/v3/src/controller/general/scope/add"
	_ "github.com/faradey/madock/v3/src/controller/general/scope/list"
	_ "github.com/faradey/madock/v3/src/controller/general/scope/set"
	_ "github.com/faradey/madock/v3/src/controller/general/service/disable"
	_ "github.com/faradey/madock/v3/src/controller/general/service/enable"
	_ "github.com/faradey/madock/v3/src/controller/general/service/list"
	_ "github.com/faradey/madock/v3/src/controller/general/setup"
	_ "github.com/faradey/madock/v3/src/controller/general/setup/env"

	// Platform setup handlers (self-register with the setup registry)
	_ "github.com/faradey/madock/v3/src/controller/custom/setup"
	_ "github.com/faradey/madock/v3/src/controller/magento/setup"
	_ "github.com/faradey/madock/v3/src/controller/prestashop/setup"
	_ "github.com/faradey/madock/v3/src/controller/shopify/setup"
	_ "github.com/faradey/madock/v3/src/controller/shopware/setup"
	_ "github.com/faradey/madock/v3/src/controller/general/snapshot/create"
	_ "github.com/faradey/madock/v3/src/controller/general/snapshot/restore"
	_ "github.com/faradey/madock/v3/src/controller/general/ssl"
	_ "github.com/faradey/madock/v3/src/controller/general/start"
	_ "github.com/faradey/madock/v3/src/controller/general/status"
	_ "github.com/faradey/madock/v3/src/controller/general/stop"
	_ "github.com/faradey/madock/v3/src/controller/magento"
	_ "github.com/faradey/madock/v3/src/controller/magento/cloud"
	_ "github.com/faradey/madock/v3/src/controller/magento/mftf"
	_ "github.com/faradey/madock/v3/src/controller/magento/n98"
	_ "github.com/faradey/madock/v3/src/controller/prestashop"
	_ "github.com/faradey/madock/v3/src/controller/shopify"
	_ "github.com/faradey/madock/v3/src/controller/shopify/frontend"
	_ "github.com/faradey/madock/v3/src/controller/shopify/web"
	_ "github.com/faradey/madock/v3/src/controller/shopware"
	_ "github.com/faradey/madock/v3/src/helper/compress"
)
