{{{template "snippets/dockerfile/common/header-ubuntu" .}}}
{{{template "snippets/dockerfile/common/cron" .}}}
{{{template "snippets/dockerfile/common/mkdir" .}}}
{{{template "snippets/dockerfile/common/chown" .}}}
{{{template "snippets/dockerfile/common/cleanup" .}}}
{{{template "snippets/dockerfile/common/footer" .}}}