{{{template "snippets/dockerfile/common/header-ubuntu" .}}}
{{{template "snippets/dockerfile/ruby/packages" .}}}
{{{template "snippets/dockerfile/common/nodejs" .}}}
{{{template "snippets/dockerfile/common/cron" .}}}
{{{template "snippets/dockerfile/common/mkdir" .}}}
{{{template "snippets/dockerfile/common/chown" .}}}
{{{template "snippets/dockerfile/common/cleanup" .}}}
{{{template "snippets/dockerfile/ruby/footer" .}}}