{{{include snippets/dockerfile/common/header-ubuntu}}}
{{{include snippets/dockerfile/ruby/packages}}}
{{{include snippets/dockerfile/common/cron}}}
{{{include snippets/dockerfile/common/mkdir}}}
{{{include snippets/dockerfile/common/chown}}}
{{{include snippets/dockerfile/common/cleanup}}}
{{{include snippets/dockerfile/ruby/footer}}}