{{{template "snippets/docker-compose/container-name.yml" .}}}
services:
  {{{- template "snippets/docker-compose/nginx.yml" .}}}
  {{{- template "snippets/docker-compose/nodejs.yml" .}}}
  {{{- template "snippets/docker-compose/storefront.yml" .}}}
  {{{- template "snippets/docker-compose/db.yml" .}}}
  {{{- template "snippets/docker-compose/db-postgresql.yml" .}}}
  {{{- template "snippets/docker-compose/redis.yml" .}}}
  {{{- template "snippets/docker-compose/meilisearch.yml" .}}}
  {{{- template "snippets/docker-compose/valkey.yml" .}}}
  {{{- template "snippets/docker-compose/memcached.yml" .}}}
  {{{- template "snippets/docker-compose/rabbitmq.yml" .}}}
  {{{- template "snippets/docker-compose/pgadmin.yml" .}}}
  {{{- template "snippets/docker-compose/claude.yml" .}}}
  {{{- template "snippets/docker-compose/worker.yml" .}}}

{{{template "snippets/docker-compose/volumes.yml" .}}}
{{{template "snippets/docker-compose/networks.yml" .}}}
