{{{include snippets/dockerfile/golang/header}}}
{{{include snippets/dockerfile/common/cron}}}
{{{include snippets/dockerfile/common/mkdir}}}
{{{include snippets/dockerfile/golang/chown}}}
{{{include snippets/dockerfile/common/cleanup}}}
{{{include snippets/dockerfile/golang/footer}}}