{{{template "snippets/dockerfile/golang/header" .}}}
{{{template "snippets/dockerfile/common/nodejs" .}}}
{{{template "snippets/dockerfile/common/cron" .}}}
{{{template "snippets/dockerfile/common/mkdir" .}}}
{{{template "snippets/dockerfile/golang/chown" .}}}
{{{template "snippets/dockerfile/common/cleanup" .}}}
{{{template "snippets/dockerfile/golang/footer" .}}}