//go:build e2e

package e2e

import (
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// TestStoppingOneProjectLeavesTheOthersServed is about blast radius.
//
// The proxy is shared, and its configuration is rewritten from scratch whenever
// anything starts or stops. That makes stopping one project the moment when
// every other project's routing is regenerated by code that was invoked on
// behalf of a different project entirely — and if it gets that wrong, the whole
// machine goes dark at once rather than one site.
//
// It is also the least likely thing to be noticed in development, where people
// tend to run one project at a time.
func TestStoppingOneProjectLeavesTheOthersServed(t *testing.T) {
	install := newInstallation(t)

	staying := install.project("e2estays")
	leaving := install.project("e2eleaves")

	for _, p := range []*project{staying, leaving} {
		p.run(5*time.Minute, "setup", "-y",
			"--platform=custom",
			"--language=none",
			"--hosts="+p.name+".test",
		)
		p.run(20*time.Minute, "start")
	}

	proxyConf := filepath.Join(install.dir, "aruntime", "ctx", "proxy.conf")
	both := readFile(t, proxyConf)
	requireContains(t, both, "e2estays.test", "the routing of the project that stays")
	requireContains(t, both, "e2eleaves.test", "the routing of the project that leaves")

	leaving.run(5*time.Minute, "stop")

	// The one that stopped should be gone from the routing: a server block
	// pointing at a container that no longer exists is how a proxy answers 502
	// for a site nobody is running, or fails to reload at all.
	after := readFile(t, proxyConf)
	if strings.Contains(after, "e2eleaves.test") {
		t.Errorf("the stopped project is still routed:\n%s", after)
	}

	// And the neighbour has to be untouched — both in the file and in what the
	// proxy actually serves, which are not the same claim.
	requireContains(t, after, "e2estays.test", "the routing of the project that stayed")
	requireCertificateFor(t, "e2estays.test")
}
